accounts/urls.py

from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
    path('entrar/', views.login, name='login'),
    path('sair/', views.logout, name='logout'),
    path('recuperar-senha/',
        views.password_reset_request,
        name='password_reset'
    ),
    path('recuperar-senha-ok/', 
        auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path('recuperar-senha-completo/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password/password_reset_complete.html'
            ),
            name='password_reset_complete',
    ),
    path('recuperar-senha-confirmar/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password/password_reset_confirm.html',
        success_url=reverse_lazy("accounts:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_confirm',
        views.password_reset_request,
        name="password_reset"
    )

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('registro/', views.cliente_cadastro, name='cliente_cadastro'),
    path('atualizar/', views.cliente_atualizar, name='cliente_atualizar'),
    path('consultas/', views.consulta_lista, name='consulta_list'),
    path('consultas/criar/', views.consulta_cadastro, name='consulta_create'),
    path('consultas/editar/<int:pk>/', views.consulta_atualizar, name='consulta_update'),
    path('consultas/excluir/<int:pk>/', views.consulta_excluir, name='consulta_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('clientes/', include('clientes.urls', namespace="clientes")),
    path('medicos/', include('medicos.urls', namespace="medicos")),
]

medicos/urls.py
from django.urls import path
from . import views

app_name = 'medicos'

urlpatterns = [
    path('registro/medico/', views.medico_cadastro, name='medico_cadastro'),
    path('registro/especialidade/', views.especialidade_cadastro, name='especialidade_cadastro'),
    path('agendar/', views.agenda_cadastro, name='agendar_consulta'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_consulta_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_consulta_deletar'),
    path('minhas/consultas/', views.agenda_lista, name="agenda_lista"),
    path('admim/lista/medicos/', views.medico_lista, name="medicos_lista"),
    path('admim/lista/especialidades/', views.especialidade_lista, name="especialidade_lista")
    
]

accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager
)


class User(AbstractBaseUser, PermissionsMixin):
    
    username = models.CharField(
        'Usuário', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Informe um nome de usuário válido. '
                'Este valor deve conter apenas letras, números '
                'e os carecteres: @/./+/-/_.'
                ,  'invalid'
            )
        ], help_text='Um nome curto que será usado'+
                    ' para identificá-lo de forma única na plataforma.'
    )
    
    name = models.CharField('Nome', max_length=100)
    email = models.EmailField('E-mail', unique=True)
    is_staff = models.BooleanField('Equipe', default=False)
    is_active = models.BooleanField('Ativo', default=True)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username
    
    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(' ')[0]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class UserAdminCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'name', 'email']


class UserAdminForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'is_active', 'is_staff']

accounts/views.py
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models.query_utils import Q
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.views.generic import CreateView, UpdateView, FormView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.views import (
    LoginView, LogoutView,
    )
from .models import User
from .forms import UserAdminCreationForm


class IndexView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/index.html'
    login_url = reverse_lazy('accounts:login')
    
    def get_object(self):
        return self.request.user


class Login(LoginView):

    model = User
    template_name = 'accounts/login.html'


class Logout(LogoutView):

    template_name = 'accounts/logged_out.html'


class RegisterView(CreateView):

    model = User
    template_name = 'accounts/register.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('index')
    
    def form_valid(self, form):
        messages.info(
            self.request, "Cadastro realizado com sucesso! Faça seu login."
        )
        return super().form_valid(form)

def password_reset_request(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain':'127.0.0.1:8000',
                        'site_name': 'Django E-commerce',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(
                            subject,
                            email,
                            "admin@exemple.com",
                            [user.email],
                            fail_silently=False
                        )
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    
                    return redirect('accounts:password_reset_done')
    form = PasswordResetForm()
    return render(
        request=request, 
        template_name="accounts/password/password_reset.html",
        context={
            "form":form,
        })

class UpdateUserView(LoginRequiredMixin, UpdateView):

    model = User
    login_url = reverse_lazy('accounts:login')
    template_name = 'accounts/update_user.html'
    fields = ['name', 'email']
    success_url = reverse_lazy('accounts:index')

    def get_object(self):
        return self.request.user


class UpdatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'accounts/update_password.html'
    login_url = reverse_lazy('accounts:login')
    success_url = reverse_lazy('accounts:index')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return super(UpdatePasswordView, self).form_valid(form)




login = Login.as_view()
logout = Logout.as_view()
register = RegisterView.as_view()
update_user = UpdateUserView.as_view()
update_password = UpdatePasswordView.as_view()
index = IndexView.as_view()

accounts/templates/accounts/index.html
{% extends 'base.html'%}

{% block title %}
    Minha Conta | {{ block.super }}
{% endblock%}

{% block container %}
     <ol class="breadcrumb">
          <li><a href="{% url 'accounts:index'%}">Início</a></li>
          <li class="active">Minha Conta</li>
        </ol>
        <div class="row">
            <div class="col-md-4">
                <div class="list-group">
                  <a href="#" class="list-group-item active">Minha Conta</a>
                  <a href="{% url 'accounts:update_user'%}" class="list-group-item">Alterar Nome e Email</a>
                  <a href="{% url 'accounts:update_password'%}" class="list-group-item">Alterar Senha</a>
                  <a href="{% url 'clientes:cliente_atualizar'%}" class="list-group-item"> Dados Complementares </a>
                  <a href="{% url 'clientes:consulta_list'%}" class="list-group-item">Minhas Consultas</a>
                  {% if request.user.is_staff or request.user.is_superuser %}
                  <a href="{% url 'medicos:agenda_lista'%}" class="list-group-item">Agendas</a>
                  <a href="{% url 'medicos:medicos_lista'%}" class="list-group-item">Medicos</a>
                  <a href="{% url 'medicos:especialidade_lista'%}" class="list-group-item">Especialidade</a>
                  {% endif %}
                </div>
            </div>
            <div class="col-md-8">
            {% block accounts_container %}
                <h2>Bem vindo {{ user.name }} </h2>
            {% endblock  %}
                
            </div>
{% endblock  %}

accounts/templates/accounts/logged_out.html
{% extends "base.html" %}

{% block container %}
  <div class="jumbotron page-header">
    <p>Você saiu!</p>
      <a href="{% url 'accounts:login'%}">
        Volte para o Login.</a>
  </div>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}

Entrar | {{ block.super }} 

{% endblock title %} 
{% block container %} 

  <div class="row"> 
  <div class="col-md-8 col-md-offset-2"> 
    <div class="page-header"> 
        <h1>Entrar</h1>
        {% for error in form.non_field_errors %}
                  <div class='alert alert-danger'>
                      {{ error }}
                  </div>
        {% endfor %}
    </div>  
                <form class="form-horizontal" method="post">
                {% csrf_token %}
                    <fieldset>
                        <div class="form-group {% if form.username.errors %} has-error {% endif %}">
                          <label for="{{form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label_tag }}</label>
                          <div class="col-md-9">
                          {% render_field form.username class='form-control' placeholder='Usuário'%}
                          {% for error in form.username.errors %}
                            <span class='help-block'>{{error}}</span>
                          {%endfor%}
                          </div>
                        </div>
                        <div class="form-group {% if form.password.errors %} has-error {% endif %}">
                          <label for="{{form.password.auto_id}}id_email" class="col-md-3 control-label">{{ form.password.label }}</label>
                          <div class="col-md-9">
                            {% render_field form.password class="form-control" placeholder="Senha" %}
                            {% for error in form.password.errors %}
                                  <span class="help-block">{{ error }}</span>
                            {% endfor %}
                          </div>
                        </div>
                        <div class="form-group">
                          <div class="col-md-9 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
{% endblock container %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Registro | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Registro</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                  <label for="{{ field.auto_id }}" class="col-md-3 control-label">
                  {{ field.label }}</label>
                  <div class="col-md-9">
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Registrar</button>
                  </div>

                </div>
            </fieldset>
        </form>
        <div class="well">
          <a href="{% url 'accounts:login' %}">Se você ja possui uma conta, faça seu login.</a>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "accounts/index.html" %}

{% load widget_tweaks %}

{% block title %} Alterar Senha {% endblock %}

{% block accounts_container %}
    <h2>Alterar Senha</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label 
              for="{{ field.auto_id }}"
              class="col-md-3 control-label">
                {{ field.label }}
              </label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock %}

accounts/templates/accounts/update_user.html
{%extends 'accounts/index.html'%}

{% load widget_tweaks %}

{% block title %}
    Alterar Dados 
{% endblock %}

{% block accounts_container %}
        <h2>Alterar Dados</h2>
    <form class="form-horizontal" action="" method="post">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Salvar</button>
              </div>
            </div>
        </fieldset>
    </form>
{% endblock  %}
