accounts/urls.py

from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from django.conf import settings

from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('alterar-dados/', views.update_user, name='update_user'),
    path('alterar-senha/', views.update_password, name='update_password'),
    path('registro/', views.register, name='register'),
    path('entrar/', views.login, name='login'),
    path('sair/', views.logout, name='logout'),
    path('recuperar-senha/',
        views.password_reset_request,
        name='password_reset'
    ),
    path('recuperar-senha-ok/', 
        auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    path('recuperar-senha-completo/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/password/password_reset_complete.html'
            ),
            name='password_reset_complete',
    ),
    path('recuperar-senha-confirmar/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password/password_reset_confirm.html',
        success_url=reverse_lazy("accounts:password_reset_complete")
        ),
        name='password_reset_confirm'
    ),
    path(
        'password_reset_confirm',
        views.password_reset_request,
        name="password_reset"
    )

]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('registro/', views.cliente_cadastro, name='cliente_cadastro'),
    path('atualizar/', views.cliente_atualizar, name='cliente_atualizar'),
    path('consultas/', views.consulta_lista, name='consulta_list'),
    path('consultas/criar/', views.consulta_cadastro, name='consulta_create'),
    path('consultas/editar/<int:pk>/', views.consulta_atualizar, name='consulta_update'),
    path('consultas/excluir/<int:pk>/', views.consulta_excluir, name='consulta_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('conta/', include('accounts.urls', namespace='accounts')),
    path('clientes/', include('clientes.urls', namespace="clientes")),
    path('medicos/', include('medicos.urls', namespace="medicos")),
]

medicos/urls.py
from django.urls import path
from . import views

app_name = 'medicos'

urlpatterns = [
    path('registro/medico/', views.medico_cadastro, name='medico_cadastro'),
    path('registro/especialidade/', views.especialidade_cadastro, name='especialidade_cadastro'),
    path('agendar/', views.agenda_cadastro, name='agendar_consulta'),
    path('agendar/atualizar/<int:pk>/', views.agenda_atualizar, name='agendar_consulta_atualizar'),
    path('agendar/apagar/<int:pk>/', views.agenda_deletar, name='agendar_consulta_deletar'),
    path('minhas/consultas/', views.agenda_lista, name="agenda_lista"),
    path('admim/lista/medicos/', views.medico_lista, name="medicos_lista"),
    path('admim/lista/especialidades/', views.especialidade_lista, name="especialidade_lista")
    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %} Painel de Agendamentos {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}"media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/extra.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar navbar-fixed-top bg-danger">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index'%}" class="navbar-brand">Hospital</a>
          <button class="navbar-toggle bg-danger" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse bg-danger" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'clientes:consulta_create'%}">Marcação</a>
            </li>
            {% if user.is_staff or user.is_superuser %}
            <li>
              <a href="{% url 'medicos:agendar_consulta'%}">Grade de horários</a>
            </li>
            <li>
              <a href="{% url 'medicos:medico_cadastro'%}">Medicos</a>
            </li>
            <li>
              <a href="{% url 'medicos:especialidade_cadastro'%}">Especialidade</a>
            </li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right bg-danger" >
            {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:index' %}">Minha Conta</a></li>
              <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
            {% else %}
              <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
              <li><a href="{% url 'accounts:register' %}">Registro</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
    {% block messages %}
      {% for message in messages %}
        <div class='alert alert-{{ message.tags}}'>
        {{ message }}
        </div>
      {% endfor %}
    {% endblock messages %} 
		{% block container %} {% endblock %}
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-unstyled">
            <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
            <li><a href="">Início</a></li>
            <li><a href="">Termos e Privacidade</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="https://kit.fontawesome.com/c2a3297ec9.js" crossorigin="anonymous"></script>
  <script src="{% static 'assets/bootstrap.min.js'%}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

templates/form_delete.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Apagar | {{ block.super }}
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Apagar</h1>
        </div>
        <form action="" method="POST">
            <p>Deseja realmente excluir: <strong>{{ object }}</strong>?</p>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Excluir</button>
            <a href="#" onClick="history.go(-1)" class="btn btn-link"> Cancelar</a>
        </form>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html'%}
{% block container %}

    <div class="jumbotron page-header bg-dark" style="background-color: lightcoral; color: whitesmoke">
        <h1>Painel de Agendamento do Hospital</h1>
        <p>Seja bem vindo(a) nossa clinica, este é o painel de agendamentos de nosso hospital, qualquer dúvida entre em contato com nosso SAC no número (11) 2233-4455
        </p>
        <p><a class="btn btn-primary" role="button">Saiba Mais</a></p>
        
    </div>

{% endblock %}